-- cse-init/cray-mpich.lua
-- Activation module for the CSE Cray-MPICH variant (v2-cray-integrated).
-- Hand-written; not generated by Spack.

help([[
The CSE Cray-MPICH variant (v2-cray-integrated).
After loading this module, packages are available under the cse/* namespace.

NOTE: This variant requires PrgEnv-gnu to be loaded.
  module swap PrgEnv-cray PrgEnv-gnu   (if needed)
  module load cse-init/cray-mpich
  module load cse/cray-mpich cse/netcdf-fortran-mpi
]])

whatis("Name        : cse-init/cray-mpich")
whatis("Description : Activates the CSE Cray-MPICH variant for release "
             .. (os.getenv("CSE_RELEASE_DEFAULT") or "<unset>"))

family("cse_init")

local cse_release = os.getenv("CSE_RELEASE_DEFAULT") or "2026_04"
local shared_path = os.getenv("CSE_SHARED_PATH")     or "/shared_path"
local variant     = "v2-cray-integrated"
local cse_root    = pathJoin(shared_path, "cse", cse_release, variant)
local mod_root    = pathJoin(cse_root, "modules", "Core")

-- Sanity check: PrgEnv-gnu must be loaded before using Variant B.
if not isloaded("PrgEnv-gnu") then
    LmodMessage("CSE WARNING: PrgEnv-gnu is not loaded.\n"
             .. "  Run 'module swap PrgEnv-cray PrgEnv-gnu' before loading cse-init/cray-mpich.")
end

setenv("CSE_RELEASE", cse_release)
setenv("CSE_VARIANT", variant)
setenv("CSE_MPI",     "cray-mpich")
setenv("CSE_ROOT",    cse_root)
prepend_path("MODULEPATH", mod_root)
