#%Module1.0
# cse-init/cray-mpich.tcl
# Activation module for the CSE Cray-MPICH variant (v2-cray-integrated).
# Hand-written; not generated by Spack.  Direct Tcl translation of cray-mpich.lua.

proc ModulesHelp {} {
    puts stderr "The CSE Cray-MPICH variant (v2-cray-integrated)."
    puts stderr "After loading this module, packages are available under the cse/* namespace."
    puts stderr ""
    puts stderr "NOTE: This variant requires PrgEnv-gnu to be loaded."
    puts stderr "  module swap PrgEnv-cray PrgEnv-gnu"
    puts stderr "  module load cse-init/cray-mpich"
    puts stderr "  module load cse/cray-mpich cse/netcdf-fortran-mpi"
}

module-whatis "Name        : cse-init/cray-mpich"
module-whatis "Description : Activates the CSE Cray-MPICH variant"

conflict cse-init/cray-mpich
conflict cse-init/openmpi

set cse_release [expr { [info exists ::env(CSE_RELEASE_DEFAULT)] \
                         ? $::env(CSE_RELEASE_DEFAULT) : "2026_04" }]
set shared_path [expr { [info exists ::env(CSE_SHARED_PATH)] \
                         ? $::env(CSE_SHARED_PATH)     : "/shared_path" }]
set variant     "v2-cray-integrated"
set cse_root    "$shared_path/cse/$cse_release/$variant"
set mod_root    "$cse_root/modules/Core"

# Warn if PrgEnv-gnu is not loaded (Tcl modules does not have isloaded())
if { ! [module-info loaded PrgEnv-gnu] } {
    puts stderr "CSE WARNING: PrgEnv-gnu is not loaded."
    puts stderr "  Run 'module swap PrgEnv-cray PrgEnv-gnu' before loading cse-init/cray-mpich."
}

setenv CSE_RELEASE $cse_release
setenv CSE_VARIANT $variant
setenv CSE_MPI     cray-mpich
setenv CSE_ROOT    $cse_root
prepend-path MODULEPATH $mod_root
