#%Module1.0
# cse-init/mpich.tcl
# Activation module for the CSE MPICH variant (v2-mpich).
# Hand-written; not generated by Spack.

proc ModulesHelp {} {
    puts stderr "The CSE MPICH variant (v2-mpich)."
    puts stderr "After loading this module, packages are available under the cse/* namespace."
    puts stderr "Try:  module avail cse"
    puts stderr "      module load cse/mpich cse/hdf5-mpi cse/netcdf-fortran-mpi"
    puts stderr ""
    puts stderr "On Cray/Slingshot systems MPICH uses OFI/libfabric for the HSN automatically."
}

module-whatis "Name        : cse-init/mpich"
module-whatis "Description : Activates the CSE MPICH variant"

conflict cse-init/mpich
conflict cse-init/openmpi

set cse_release [expr { [info exists ::env(CSE_RELEASE_DEFAULT)] \
                         ? $::env(CSE_RELEASE_DEFAULT) : "2026_04" }]
set shared_path [expr { [info exists ::env(CSE_SHARED_PATH)] \
                         ? $::env(CSE_SHARED_PATH)     : "/shared_path" }]
set variant     "v2-mpich"
set cse_root    "$shared_path/cse/$cse_release/$variant"
set mod_root    "$cse_root/modules"

setenv CSE_RELEASE $cse_release
setenv CSE_VARIANT $variant
setenv CSE_MPI     mpich
setenv CSE_ROOT    $cse_root
prepend-path MODULEPATH $mod_root
