-- cse-init/mpich.lua
-- Activation module for the CSE MPICH variant (v2-mpich).
-- Hand-written; not generated by Spack.

help([[
The CSE MPICH variant (v2-mpich).
After loading this module, packages are available under the cse/* namespace.
Try:  module avail cse
      module load cse/mpich cse/hdf5-mpi cse/netcdf-fortran-mpi

On Cray/Slingshot systems MPICH is built with OFI/libfabric support and uses
the native high-speed network automatically.

Phase 2 (future): set CSE_MPICH_SPLICE=1 before loading to swap in cray-mpich
at runtime via MPICH ABI compatibility (not yet implemented).
]])

whatis("Name        : cse-init/mpich")
whatis("Description : Activates the CSE MPICH variant for release "
             .. (os.getenv("CSE_RELEASE_DEFAULT") or "<unset>"))

family("cse_init")

local cse_release = os.getenv("CSE_RELEASE_DEFAULT") or "2026_04"
local shared_path = os.getenv("CSE_SHARED_PATH")     or "/shared_path"
local variant     = "v2-mpich"
local cse_root    = pathJoin(shared_path, "cse", cse_release, variant)
local mod_root    = pathJoin(cse_root, "modules", "Core")

setenv("CSE_RELEASE", cse_release)
setenv("CSE_VARIANT", variant)
setenv("CSE_MPI",     "mpich")
setenv("CSE_ROOT",    cse_root)
prepend_path("MODULEPATH", mod_root)
