-- cse-init/openmpi.lua
-- Activation module for the CSE OpenMPI variant (v1-openmpi).
-- Hand-written; not generated by Spack.

help([[
The CSE OpenMPI variant (v1-openmpi).
After loading this module, packages are available under the cse/* namespace.
Try:  module avail cse
      module load cse/openmpi cse/hdf5-mpi cse/netcdf-fortran-mpi
]])

whatis("Name        : cse-init/openmpi")
whatis("Description : Activates the CSE OpenMPI variant for release "
             .. (os.getenv("CSE_RELEASE_DEFAULT") or "<unset>"))

family("cse_init")

local cse_release = os.getenv("CSE_RELEASE_DEFAULT") or "2026_04"
local shared_path = os.getenv("CSE_SHARED_PATH")     or "/shared_path"
local variant     = "v1-openmpi"
local cse_root    = pathJoin(shared_path, "cse", cse_release, variant)
local mod_root    = pathJoin(cse_root, "modules")

setenv("CSE_RELEASE", cse_release)
setenv("CSE_VARIANT", variant)
setenv("CSE_MPI",     "openmpi")
setenv("CSE_ROOT",    cse_root)
prepend_path("MODULEPATH", mod_root)
