-- cse-init/openmpi.lua
-- Activation module for the CSE Open MPI variant (v1-minimal-externals).
-- Hand-written; not generated by Spack.
-- Place this file in a path that is on MODULEPATH from login
-- (e.g. via an /etc/profile.d snippet or site module-system configuration).

help([[
The CSE Open MPI variant (v1-minimal-externals).
After loading this module, packages are available under the cse/* namespace.
Try:  module avail cse
      module load cse/openmpi cse/hdf5-mpi cse/netcdf-fortran-mpi
]])

whatis("Name        : cse-init/openmpi")
whatis("Description : Activates the CSE Open MPI variant for release "
             .. (os.getenv("CSE_RELEASE_DEFAULT") or "<unset>"))

-- Declare family so that loading cse-init/cray-mpich automatically unloads this.
family("cse_init")

local cse_release = os.getenv("CSE_RELEASE_DEFAULT") or "2026_04"
local shared_path = os.getenv("CSE_SHARED_PATH")     or "/shared_path"
local variant     = "v1-minimal"
local cse_root    = pathJoin(shared_path, "cse", cse_release, variant)
-- The Core subdirectory is the conventional Lmod root Spack writes when
-- hierarchy: [] is set.  Confirm this name against the Spack version in use.
local mod_root    = pathJoin(cse_root, "modules", "Core")

setenv("CSE_RELEASE", cse_release)
setenv("CSE_VARIANT", variant)
setenv("CSE_MPI",     "openmpi")
setenv("CSE_ROOT",    cse_root)
prepend_path("MODULEPATH", mod_root)
