#%Module1.0
# cse-init/openmpi.tcl
# Activation module for the CSE Open MPI variant (v1-minimal-externals).
# Hand-written; not generated by Spack.  Direct Tcl translation of openmpi.lua.

proc ModulesHelp {} {
    puts stderr "The CSE Open MPI variant (v1-minimal-externals)."
    puts stderr "After loading this module, packages are available under the cse/* namespace."
    puts stderr "Try:  module avail cse"
    puts stderr "      module load cse/openmpi cse/hdf5-mpi cse/netcdf-fortran-mpi"
}

module-whatis "Name        : cse-init/openmpi"
module-whatis "Description : Activates the CSE Open MPI variant"

# Mutual exclusion: only one cse-init variant may be loaded at a time.
conflict cse-init/openmpi
conflict cse-init/cray-mpich

set cse_release [expr { [info exists ::env(CSE_RELEASE_DEFAULT)] \
                         ? $::env(CSE_RELEASE_DEFAULT) : "2026_04" }]
set shared_path [expr { [info exists ::env(CSE_SHARED_PATH)] \
                         ? $::env(CSE_SHARED_PATH)     : "/shared_path" }]
set variant     "v1-minimal"
set cse_root    "$shared_path/cse/$cse_release/$variant"
set mod_root    "$cse_root/modules/Core"

setenv CSE_RELEASE $cse_release
setenv CSE_VARIANT $variant
setenv CSE_MPI     openmpi
setenv CSE_ROOT    $cse_root
prepend-path MODULEPATH $mod_root
