#%Module1.0
# cse-init/openmpi.tcl
# Activation module for the CSE OpenMPI variant (v1-openmpi).
# Hand-written; not generated by Spack.

proc ModulesHelp {} {
    puts stderr "The CSE OpenMPI variant (v1-openmpi)."
    puts stderr "After loading this module, packages are available under the cse/* namespace."
    puts stderr "Try:  module avail cse"
    puts stderr "      module load cse/openmpi cse/hdf5-mpi cse/netcdf-fortran-mpi"
}

module-whatis "Name        : cse-init/openmpi"
module-whatis "Description : Activates the CSE OpenMPI variant"

conflict cse-init/openmpi
conflict cse-init/mpich

set cse_release [expr { [info exists ::env(CSE_RELEASE_DEFAULT)] \
                         ? $::env(CSE_RELEASE_DEFAULT) : "2026_04" }]
set shared_path [expr { [info exists ::env(CSE_SHARED_PATH)] \
                         ? $::env(CSE_SHARED_PATH)     : "/shared_path" }]
set variant     "v1-openmpi"
set cse_root    "$shared_path/cse/$cse_release/$variant"
set mod_root    "$cse_root/modules"

setenv CSE_RELEASE $cse_release
setenv CSE_VARIANT $variant
setenv CSE_MPI     openmpi
setenv CSE_ROOT    $cse_root
prepend-path MODULEPATH $mod_root
